config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
  validates :last_name, presence: true
  validates :birth_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
# Controller Students
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit

  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student
    else
      render 'new'
    end
  end

  private

    def student_params
      params.require(:student).permit(:name, :last_name, :birth_date)
    end
end

app/controllers/welcome_controller.rb
# Controller welcome
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>Lista de estudiantes</h1>

<table>
  <th>
    <tr>
      Nombre
    </tr>
    <tr>
      Apellido
    </tr>
    <tr>
      Fecha Nacimiento
    </tr>
  </th>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.last_name %></td>
      <td><%= student.birth_date %>
    </tr>
  <% end %>
</table>

<%=  link_to 'Registrar nuevo estudiante', new_student_path %>

app/views/students/new.html.erb
<h1>Registra nuevo estudiante</h1>

<%= form_for :student, url: students_path do |f| %>
  <% if @student.errors.any? %>
    <div id="errors_explanation" >
      <h2>
        <%= "Se encontraron errores en los datos!" %>
      </h2>
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>

      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :birth_date %><br />
    <%= f.text_field :birth_date %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Ver estudiantes', students_path %>

app/views/students/show.html.erb
<h1>Estudiante Registrado</h1>
<p>
  <strong>Nombre:</strong>
    <%= @student.name.concat(" #{@student.last_name}") %>
</p>
<p>
  <strong>Fecha Nacimiento</strong>
    <%= @student.birth_date %>
</p>

<%= link_to 'Lista de estudiantes', students_path %>

app/views/welcome/index.html.erb
<h1>Ejemplo para control de alumnos</h1>
<p>
  Este ejemplo pretende realizar un practica con controladores y modelos con Ruby on Rails
</p>

<%= link_to 'Lista de estudiantes', controller: 'students' %>